# Welcome to Jekyll!
#

# Site settings
title: Biram kulturu.
description: |
  Na našem TV-u nema signala, frekvenciju birajte sami. Ugasite pretplatu na plasiran sadržaj i pretplatite se na KULTURU.
owner: Biram Kulturu # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: kostastojiljkovic@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ichooseofficial.com/" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/biramkulturu/i_choose_official
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

exclude:
         - vendor
         - Gemfile
         - Gemfile.lock
         - node_modules
         - gulpfile.js
         - package.json
         
encoding: utf-8
